- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags:
    - apt

- name: Add a list of repositories from PPA and install its signing key on Ubuntu target
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:ondrej/php
  tags:
    - apt

- name: Install a list of packages
  become: true
  ansible.builtin.apt:
    pkg: # sorted alphabetically
      - apache2
      - chromium-browser # transitional "snap" package
      - curl
      - dbus-x11
      - firefox
      - git
      - libapache2-mod-php8.2
      - nano
      - nodejs
      - mariadb-client
      - mariadb-server
      - php8.2
      - php8.2-cli
      - php8.2-mbstring
      - php8.2-mysql
      - php8.2-xml
      - silversearcher-ag # :)
      - software-properties-common
      - vim
      - virtualbox-guest-additions-iso # for shared clipboard and video support (https://www.virtualbox.org/manual/ch04.html)
      - wget
      - zeal
      - zsh
    state: latest
  tags:
    - apt

- name: "Read Checksum"
  shell: curl https://getcomposer.org/download/latest-stable/composer.phar.sha256
  register: composer_checksum
  changed_when: false
  tags:
    - apt

- name: "Download PHAR file"
  become: true
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: /usr/local/bin/composer
    force: yes
    checksum: "sha256:{{ composer_checksum.stdout }}"
    mode: '0755'
  tags:
    - apt

- name: "Read composer version"
  shell: composer -V
  register: composer_version
  changed_when: false
  tags:
    - apt
    - apt.test

- debug:
    var: composer_version.stdout
  tags:
    - apt
    - apt.test

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: yes
  tags:
    - apt

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: yes
  tags:
    - apt
