- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags:
    - apt


- name: Install a list of packages
  become: true
  ansible.builtin.apt:
    pkg: # sorted alphabetically
      - apache2
      - chromium-browser # transitional "snap" package
      - curl
      - dbus-x11
      - firefox
      - git
      - libapache2-mod-php8.2
      - nano
      - nodejs
      - mariadb-client
      - mariadb-server
      - silversearcher-ag # :)
      - software-properties-common
      - vim
      - virtualbox-guest-additions-iso # for shared clipboard and video support (https://www.virtualbox.org/manual/ch04.html)
      - wget
      - zeal
      - zsh
    state: latest
  tags:
    - apt


- debug:
    var: composer_version.stdout
  tags:
    - apt
    - apt.test

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: yes
  tags:
    - apt

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: yes
  tags:
    - apt
