- include_vars: vars/common-vars.yml
  tags: always

- include_tasks: hostname.yml
  tags:
    - hostname
    - hostname.test

- include_tasks: apt.yml
  tags:
    - apt
    - apt.test

- include_tasks: users.yml
  tags:
    - users
    - users.test

