- include_vars: vars/common-vars.yml
  tags: always

- include_tasks: hostname.yml
  tags:
    - hostname
    - hostname.test

- include_tasks: apt.yml
  tags:
    - apt
    - apt.test

- include_tasks: users.yml
  tags:
    - users
    - users.test

- include_tasks: skills17.yml
  tags:
    - skills17
    - skills17.test

- include_tasks: desktop-shortcuts.yml
  tags:
    - custom
    - custom.test

- include_tasks: apache.yml
  tags:
    - apache
    - apache.test

- include_tasks: atom.yml
  tags:
    - atom
    - atom.test

- include_tasks: zeal.yml
  tags:
    - zeal
    - zeal.test
