- debug:
    msg: "{{ student.user }}"
  tags:
    - users

- name: Add the `{{ student.user }}` user
  become: true
  ansible.builtin.user:
    name: "{{ student.user }}"
    comment: The student account
    password: "{{ student.pass | password_hash('sha512', student.hash) }}"
    shell: /bin/zsh
    state: present
  tags:
    - users

- name: Configure zsh for `{{ student.user }}`
  become: true
  ansible.builtin.template:
    src: zshrc.j2
    dest: "/home/{{ student.user }}/.zshrc"
    owner: "{{ student.user }}"
    group: "{{ student.user }}"
    mode: '0644'
  tags:
    - users

- name: Enable automatic login
  become: true
  ansible.builtin.replace:
    path: /etc/gdm3/custom.conf
    after: '# Enabling automatic login'
    regexp: '^#  AutomaticLoginEnable = true'
    replace: 'AutomaticLoginEnable = true'
  tags:
    - users

- name: Enable automatic login for `{{ student.user }}`
  become: true
  ansible.builtin.replace:
    path: /etc/gdm3/custom.conf
    after: 'AutomaticLoginEnable = true'
    regexp: '^#  AutomaticLogin = user1'
    replace: "AutomaticLogin = {{ student.user }}"
  tags:
    - users

